openapi: 3.0.0
info:
  title: API de SwapInfo
  version: 1.0.0
  description: Descripción de la API de SwapInfo

paths:
  /swapi/planeta/{id}:
    get:
      summary: Obtener información de un planeta por su ID desde SWAPI
      parameters:
        - in: path
          name: id
          required: true
          description: ID del planeta
          schema:
            type: string
      responses:
        '200':
          description: Éxito
          content:
            application/json:
              schema:
                type: object
                properties:
                  nombre:
                    type: string
                  periodo_rotacion:
                    type: string
                  periodo_orbital:
                    type: string
                  diametro:
                    type: string
                  clima:
                    type: string
                  gravedad:
                    type: string
                  terreno:
                    type: string
                  agua_superficial:
                    type: string
                  poblacion:
                    type: string
                  residentes:
                    type: array
                    items:
                      type: string
                      format: uri
                  peliculas:
                    type: array
                    items:
                      type: string
                      format: uri
                  creado:
                    type: string
                    format: date-time
                  editado:
                    type: string
                    format: date-time
                  url:
                    type: string
                    format: uri
  /planeta/{id}:
    get:
      summary: Obtener información de un planeta por su ID desde AWS
      parameters:
        - in: path
          name: id
          required: true
          description: ID del planeta
          schema:
            type: string
      responses:
        '200':
          description: Éxito
          content:
            application/json:
              schema:
                type: object
                properties:
                  nombre:
                    type: string
                  periodo_rotacion:
                    type: string
                  periodo_orbital:
                    type: string
                  diametro:
                    type: string
                  clima:
                    type: string
                  gravedad:
                    type: string
                  terreno:
                    type: string
                  agua_superficial:
                    type: string
                  poblacion:
                    type: string
                  residentes:
                    type: array
                    items:
                      type: string
                      format: uri
                  peliculas:
                    type: array
                    items:
                      type: string
                      format: uri  # Si son URLs, también puedes definir el formato
                  creado:
                    type: string
                    format: date-time  # Define el formato de fecha y hora
                  editado:
                    type: string
                    format: date-time
                  url:
                    type: string
                    format: uri
  /planeta:
    post:
      summary: Agregar un nuevo planeta a través de AWS
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: string
      responses:
        '200':
          description: Éxito
          content:
            application/json:
              schema:
                type: string
        '500':
          description: Error del servidor
          content:
            application/json:
              schema:
                type: string
